Avoid showing new windows on Windows
pypa/virtualenv pull request #1929
Opened 2020-08-24 06:26 UTC by gaborbernat

2020-08-24 06:50 UTC, pfmoore requested changes

2020-08-24 06:50 UTC, pfmoore commented on src/virtualenv/seed/wheels/periodic_update.py
> +        kwargs["creationflags"] = DETACHED_PROCESS | CREATE_NO_WINDOW
This won't work - the `CREATE_NO_WINDOW` flag needs to be passed by itself, it's ignored if passed along with `DETACHED_PROCESS`.

2020-08-24 07:13 UTC, uranusjr approved these changes

2020-08-24 07:14 UTC, pfmoore approved these changes

2020-08-31 16:42 UTC, pradyunsg commented
@gaborbernat Anything blocking the merge on this?

2020-08-31 18:39 UTC, merged