Allow unfunctioing pydoc to fail
pypa/virtualenv pull request #2049
Opened 2021-01-12 09:01 UTC by d125q

Otherwise, one cannot activate a virtualenv under Zsh with set -e.

As an example,
```shell-session
$ zsh -c 'set -ex; source /path/to/virtualenv/bin/activate; echo activated'
+zsh:1> source /path/to/virtualenvbin/activate
+/path/to/virtualenvbin/activate:5> [ '' '=' /path/to/virtualenvbin/activate ']'
+/path/to/virtualenvbin/activate:47> deactivate nondestructive
+deactivate:1> unset -f pydoc
```
fails with exit code 1 because there is nothing to unset.  (My Zsh version is `zsh 5.8.0.2-dev (x86_64-pc-linux-gnu)`.)

2021-01-12 09:28 UTC, gaborbernat requested changes
Please add a changelog entry, thanks!

2021-01-12 09:57 UTC, d125q commented
> Please add a changelog entry, thanks!

Added; thanks likewise!

2021-01-12 10:04 UTC, gaborbernat approved these changes
![](https://media.tenor.co/images/bee8bf98cd1c1d9659af200f8aa71206/tenor.gif)

2021-01-12 10:04 UTC, merged

2021-01-13 09:05 UTC, gaborbernat commented
Released now via https://virtualenv.pypa.io/en/latest/changelog.html#v20-3-1-2021-01-13