Fix for Python 2 framework support on macOS 12.3
pypa/virtualenv pull request #2325
Opened 2022-03-29 08:01 UTC by nickhutchinson

virtualenv's trick of adding a symlink to the Python dylib -- `/path/to/Python.framework/Versions/2.7/Python` -- in the virtualenv root and rewriting the dependent dylib list of `<virtualenv>/bin/python` with the path of this symlink no longer works in macOS 12.3.

As of macOS 12.3, when <https://github.com/python/cpython/blob/v2.7.18/Modules/getpath.c> computes `sys.prefix`, it ends up resolving the symlink. The result is that `sys.prefix` points to the Python framework, e.g.  `/Libraries/Frameworks/Python.framework/Versions/2.7` instead of at the virtualenv root.

To mitigate this, add a _copy_ of the Python dylib into the virtualenv instead of a symlink. To placate code signing, add a symlink to the `Resources` dir so the `Info.plist` file is accessible.

Tested on macOS 12.3 on an Intel and M1 mac.

Fixes: #2284

### Thanks for contributing, make sure you address all the checklists (for details on how see
[development documentation](https://virtualenv.pypa.io/en/latest/development.html#development))!

- [x] ran the linter to address style issues (``tox -e fix_lint``)
- [x] wrote descriptive pull request text
- [ ] ensured there are test(s) validating the fix
- [x] added news fragment in ``docs/changelog`` folder
- [ ] updated/extended the documentation

2022-03-29 08:09 UTC, gaborbernat commented on docs/changelog/2284.bugfix.rst
> +Fix for creating virtualenvs from a Python 2.7 framework on macOS 12.3 - by :user:`nickhutchinson`.
I consider this a feature rather than a bugfix, so let's move it to a feature file 👍 something like support for macos 12.3 👍

2022-03-29 08:25 UTC, nickhutchinson commented
I want to try and test in a macOS 12.2 VM -- rereading the original thread more carefully, it might be that the behaviour change was actually in macOS 12.0, and Apple's Python 2 (removed in macOS 12.3) had some custom patches to work around the issue.

2022-04-02 20:30 UTC, nickhutchinson commented
> I want to try and test in a macOS 12.2 VM -- rereading the original thread more carefully, it might be that the behaviour change was actually in macOS 12.0, and Apple's Python 2 (removed in macOS 12.3) had some custom patches to work around the issue.

This does seem to be the case, and I've updated the PR description and commit message to be more accurate. Virtualenv worked with Apple's Python 2.7 on macOS [12,12.3) -- though _not_ with Python 2.7 distributions from python.org  -- likely because they applied a bunch of custom patches, including this one: <https://github.com/apple-oss-distributions/python/blob/python-170.80.2/2.7/fix/getpath.c.ed>.

2022-04-07 04:39 UTC, hynek commented
> I want to try and test in a macOS 12.2 VM -- rereading the original thread more carefully, it might be that the behaviour change was actually in macOS 12.0, and Apple's Python 2 (removed in macOS 12.3) had some custom patches to work around the issue.

This is 100% the case; I remember switching to Apple's 2.7 because "suddenly" virtualenv was broken and forgetting to further investigate.

2022-04-11 06:04 UTC, gaborbernat approved these changes

2022-04-11 06:08 UTC, gaborbernat requested changes
@nickhutchinson can you make the CI pass? thanks!

2022-04-11 07:54 UTC, merged

2022-09-20 17:08 UTC, evangrim commented
@hynek You mentioned switching to Apple's 2.7. How did you manage that? I'm asking as an end user of an old virtualenv project, and I understand little about virtualenv or config related to it.

2022-09-21 05:00 UTC, hynek commented
@evangrim What I meant was that I didn't install Python 2 myself anymore & used the one that came with macOS. The point is moot tho, because Apple doesn't ship a Python 2 anymore.

Nowadays, the [pyenv version](https://github.com/pyenv/pyenv) works just fine with current virtualenv releases.