CI: Update actions and OSes, weekly cron job
pypa/virtualenv pull request #2346
Opened 2022-05-24 11:49 UTC by EwoutH

A bit of maintenance on the CI. This PR consists of 3 commits:

- _Update used actions to v3_
   Update the checkout, setup-python and upload-/download-artifact actions to v3

 - _Use the latest stable version of each OS_
   Use the latest stable version of Ubuntu, macOS and Windows. Currently those are Ubuntu 20.04, macOS 11 and Windows Server 2022, which means macOS is directly updated from 10.15 to 11, and all OS will be kept up to date.

   The scheduled cron job will catch any breaking changes due to changing environments (which aren't likely).
 - _Run cron job weekly (instead of daily)_
   Once a week is enough to catch changes in dependencies or the environment. Running this extensive CI daily is quite power intensive and thus has a large costs and environmental impact.

2022-05-30 05:13 UTC, EwoutH commented
Hi @gaborbernat, would you be able to enable the workflow and take a look at this PR?

2022-05-31 00:24 UTC, gaborbernat requested changes
All three of these changes deserve their own PR, ideally with an issue discussing the change and approach to tackle it. In the current form I cannot accept this PR.

2022-05-31 00:24 UTC, gaborbernat commented on .github/workflows/check.yml
> -    - cron: "0 8 * * *"
I'm -1 on this.

2022-05-31 00:24 UTC, gaborbernat commented on .github/workflows/check.yml
>        - uses: pre-commit/action@v2.0.3
For this, a better solution is to set up dependabot to do it automatically, in future too.

2022-05-31 00:24 UTC, gaborbernat commented on .github/workflows/check.yml
> -          - windows-2022
I like the explicit nature here of the version used then this link. If some explicit version needs bumped we can do that separately.

2022-05-31 00:24 UTC, closed without merging