Ensures activate.bat can handle Unicode contents
pypa/virtualenv pull request #2416
Opened 2022-09-10 22:57 UTC by OmerFI

### activate.bat is UTF-8 encoded but uses current console codepage.

This issue was encountered first in [venv](https://docs.python.org/3/library/venv.html).
You can see the issue created for venv module on: https://github.com/python/cpython/issues/76590
And the original pull request for the venv module: https://github.com/python/cpython/pull/5757

I just added some code that applies the [original PR](https://github.com/python/cpython/pull/5757) that is made for the venv module to solve this issue. The code I added is somewhat the same as [original commit](https://github.com/python/cpython/pull/5757/files#diff-7c85d7383e780aa67d394c766ca77aa0e0b4988a1b042f56232fcd35ee0a7a91) except added `@` signs

Closes #2414

2022-09-15 16:33 UTC, gaborbernat reviewed
Can we add test for this? 🤔

2022-09-15 22:51 UTC, OmerFI commented
Actually, I don't know much about pytest 🤔

2022-09-19 16:58 UTC, gaborbernat requested changes
Can you add a changelog entry?

2022-09-20 19:15 UTC, OmerFI commented
I think we now don't have to change the character code page to 65001 in [_get_test_lines](https://github.com/pypa/virtualenv/blob/main/tests/unit/activation/test_batch.py#L23-L25) function.

We can replace this:
```py
        def _get_test_lines(self, activate_script):
            # for BATCH utf-8 support need change the character code page to 650001
            return ["@echo off", "", "chcp 65001 1>NUL"] + super()._get_test_lines(activate_script)
```
to this:
```py
        def _get_test_lines(self, activate_script):
            return ["@echo off", ""] + super()._get_test_lines(activate_script)
```

2022-09-27 12:32 UTC, OmerFI commented
> I think we now don't have to change the character code page to 65001 in [_get_test_lines](https://github.com/pypa/virtualenv/blob/main/tests/unit/activation/test_batch.py#L23-L25) function.
> 
> We can replace this:
> 
> ```python
>         def _get_test_lines(self, activate_script):
>             # for BATCH utf-8 support need change the character code page to 650001
>             return ["@echo off", "", "chcp 65001 1>NUL"] + super()._get_test_lines(activate_script)
> ```
> 
> to this:
> 
> ```python
>         def _get_test_lines(self, activate_script):
>             return ["@echo off", ""] + super()._get_test_lines(activate_script)
> ```

Actually, this is wrong. Because a file called `script.bat` is created during the test and this file also should handle Unicode contents.

2022-09-27 12:42 UTC, OmerFI commented
I think we should use `utf-8` in windows not `ascii` to test this Unicode support, so I made these changes in the last [commit](https://github.com/pypa/virtualenv/pull/2416/commits/1dd1335a43e365ea42d49aa27fd17c083423fdd5):
```diff
- encoding = "ascii" if IS_WIN else sys.getfilesystemencoding()
+ encoding = sys.getfilesystemencoding()
```

But, when I run tests, it fails in Powershell tests. That can be because of PowerShell file does not handle Unicode contents also.

So I am making this Pull request draft.

2022-09-28 18:27 UTC, gaborbernat commented
> But, when I run tests, it fails in Powershell tests. That can be because of PowerShell file does not handle Unicode contents also.
> 
> So I mark this pull request as draft until there is a solution to this problem.

You'll need to come up with a solution for this to land 🤔

2022-10-25 05:00 UTC, gaborbernat commented
Closing dut to being stalled, we can reopen if someone picks it up again.

2022-10-30 22:50 UTC, closed without merging