Fix test_csh when running with the original csh
pypa/virtualenv pull request #2418
Opened 2022-09-14 15:09 UTC by kulikjak

This fixes the issue with **test_csh** when running with the original `csh` rather than today widely used `tcsh`.

`tcsh` on Linux (`csh` is just a symlink to `tcsh`) or Solaris:
```shell
$ echo "echo 'test'" | tcsh -i
[me@mymachine ~]$ test
[me@mymachine ~]$ exit
$
```
and `csh` on Solaris:
```shell
$ echo "echo 'test'" | csh -i
mymachine-i386-25280% test
mymachine-i386-25280% $
```
By adding a forced newline to the prompt, we can be sure that at least one will be there, and thus the prompt won't 'leak' to the next line.

I am wondering whether it makes sense to add a similar **test_tcsh** test that would explicitly run `tcsh`. On Linux, it would do the same thing, but on platforms where both versions of the shell are available, it would test both.

Closes #2409 

- [x] ran the linter to address style issues (`tox -e fix_lint`)
- [x] wrote descriptive pull request text

2022-09-15 16:33 UTC, gaborbernat requested changes
You'll need to fix the CI.

2022-09-19 05:50 UTC, kulikjak commented
The one failure again doesn't seem to be related to my change.

2022-09-19 16:58 UTC, gaborbernat requested changes
Can you add a changelog entry?

2022-09-20 14:16 UTC, kulikjak commented
Sure, done.

2022-10-25 05:00 UTC, merged