Don't install setuptools and wheel on Python 3.12+ environments
pypa/virtualenv pull request #2558
Opened 2023-04-25 15:12 UTC by chrysle

Note this is my first little code contribution, so please be patient. Closes #2487 

- [x] ran the linter to address style issues (`tox -e fix`)
- [x] wrote descriptive pull request text
- [ ] ensured there are test(s) validating the fix
- [ ] added news fragment in `docs/changelog` folder
- [x] updated/extended the documentation

2023-04-25 16:30 UTC, gaborbernat requested changes

2023-04-25 16:30 UTC, gaborbernat commented on src/virtualenv/seed/embed/base_embed.py
> +PYTHON_VERSION = sys.version_info.minor
Please inline these globals 👍

2023-04-25 18:03 UTC, gaborbernat commented on src/virtualenv/seed/embed/base_embed.py
> +                default=True if (PYTHON_VERSION >= 12) and (distribution in OPTIONAL_DISTS) else False,
See the interpreter object that's a parameter here

2023-04-26 12:27 UTC, chrysle commented
Thanks for the review. Updated.

2023-04-26 16:42 UTC, gaborbernat requested changes
You also need a test.

2023-04-26 16:42 UTC, gaborbernat commented on docs/user_guide.rst
> +enables you to install additional python packages into the created virtual environment (by invoking pip). Installing :pypi:`setuptools` and :pypi:`wheel` is disabled by default on Python 3.12+ enviro
Align at 120 cahracters.

2023-04-26 16:42 UTC, gaborbernat commented on src/virtualenv/seed/embed/base_embed.py
> +PERIODIC_UPDATE_ON_BY_DEFAULT, OPTIONAL_DISTS = True, {"wheel", "setuptools"}
Inline OPTIONAL_DISTS; we don't need a global for this

2023-04-26 16:42 UTC, gaborbernat commented on src/virtualenv/seed/embed/base_embed.py
> +                if (float(interpreter.version_str.rsplit(".", 1)[0]) >= 12) and (distribution in OPTIONAL_DISTS)
don't use version_str, use version instead

2023-04-26 16:42 UTC, gaborbernat commented on whitelist.txt
> +dists
remove dists

2023-04-26 16:57 UTC, chrysle commented
Will look into this. Sorry for producing so much review work.

2023-04-27 17:19 UTC, gaborbernat commented
Ah this will get complicated, I'll take it from here 👍

2023-04-27 17:22 UTC, chrysle commented
Thank you! I'll try to be more help next time.

2023-04-27 22:22 UTC, gaborbernat approved these changes

2023-04-27 23:36 UTC, merged