Export `VIRTUAL_ENV_PROMPT` in activation scripts (#2914)
pypa/virtualenv pull request #2606
Opened 2023-07-13 23:15 UTC by jimporter

See issue #2914. This change exports a `VIRTUAL_ENV_PROMPT` environment variable during venv activation so that users can use this in their own custom shell prompts if they like. I didn't add a test for this since I don't see any similar tests, and I'm not quite sure the bet way to go about writing one...

---

### Thanks for contributing, make sure you address all the checklists (for details on how see [development documentation](https://virtualenv.pypa.io/en/latest/development.html#development))

- [x] ran the linter to address style issues (`tox -e fix`)
- [x] wrote descriptive pull request text
- [ ] ensured there are test(s) validating the fix
- [x] added news fragment in `docs/changelog` folder
- [x] updated/extended the documentation

2023-07-13 23:19 UTC, gaborbernat approved these changes
![](https://media.tenor.com/ZBt12E1nwqQAAAAC/deploy-parksandrec.gif)

2023-07-13 23:19 UTC, gaborbernat requested changes
Please add extend the test suite to test for this.

2023-07-13 23:52 UTC, jimporter commented
> Please add extend the test suite to test for this.

I'll take a look. I'm going to mark this as a draft for now until I get tests resolved (and ideally for my second `venv` PR to merge so that I can be sure the behavior is the same between `venv` and `virtualenv`).

2023-07-14 01:07 UTC, jimporter commented
@gaborbernat Ok, hopefully these tests pass. I had to make some educated guesses for a few of the shells.

2023-07-14 15:46 UTC, gaborbernat requested changes
You'll need to make the CI pass 😊

2023-07-14 17:45 UTC, jimporter commented
@gaborbernat Ok, I think these tests should be good now. One small note is that I renamed `VIRTUAL_PROMPT` to `VIRTUAL_PREFIX` in Nushell to reduce ambiguity, though I could revert that. As far as I can tell, that variable is only there to make it easier to write a unit test (this is the variable that holds `(<env-name>) `, as opposed to `VIRTUAL_ENV_PROMPT` which holds `<env-name>`).

2023-07-14 18:23 UTC, gaborbernat approved these changes
![](https://media.tenor.com/U0aZZ02M_dkAAAAd/bored-tired.gif)

2023-07-14 22:33 UTC, merged