Fix for tests: Python 3.13.0a6 renamed pathmod to parser
pypa/virtualenv pull request #2702
Opened 2024-04-16 07:22 UTC by befeleme

This fixes https://github.com/pypa/virtualenv/issues/2671 which reappeared in alpha6 as a result of upstream renaming the attribute.

### Thanks for contributing, make sure you address all the checklists (for details on how see [development documentation](https://virtualenv.pypa.io/en/latest/development.html#development))

- [x] ran the linter to address style issues (`tox -e fix`)
- [x] wrote descriptive pull request text
- [ ] ensured there are test(s) validating the fix
- [ ] added news fragment in `docs/changelog` folder
- [ ] updated/extended the documentation

2024-04-16 23:07 UTC, gaborbernat approved these changes

2024-04-17 00:08 UTC, gaborbernat approved these changes

2024-04-17 00:18 UTC, gaborbernat requested changes
Fails on Windows, can you address please.

2024-04-17 07:26 UTC, befeleme commented
I see 4 failing checks (2x macos, ubuntu and docs), none can be attributed to these changes, windows tests pass. I don't know what to address.

2024-04-17 14:44 UTC, merged