Fix bad return code in bash activation if hashing is disabled
pypa/virtualenv pull request #2717
Opened 2024-05-08 13:52 UTC by fenkes-ibm

If hashing is disabled in bash, the `hash` command will return a nonzero return code. Since it is the last command in the script that return code will also be the "return code" of the source command, so if anyone uses

source activate.sh || die horribly

having hashing disabled will ruin their day.

Fix this by overriding the return code of `hash` if it's bad. Add tests to verify a good return code and try with and without hashing.

### Thanks for contributing, make sure you address all the checklists (for details on how see [development documentation](https://virtualenv.pypa.io/en/latest/development.html#development))

- [x] ran the linter to address style issues (`tox -e fix`)
- [x] wrote descriptive pull request text
- [x] ensured there are test(s) validating the fix
- [x] added news fragment in `docs/changelog` folder
- [x] updated/extended the documentation

2024-05-10 22:53 UTC, gaborbernat requested changes
CI failing.

2024-05-13 15:42 UTC, fenkes-ibm commented
Ah, looks like I wedged in before #2721. Rebased, let's try again.

2024-05-13 17:16 UTC, gaborbernat approved these changes
![](https://media.tenor.co/images/9de7fd256ae2d94410a0b8e08c941071/tenor.gif)

2024-05-13 17:44 UTC, fenkes-ibm commented
brew@3.11 on macos timed out? :raised_eyebrow: maybe it just had a bad day and needs a rerun?

2024-05-13 18:02 UTC, merged