Add free-threaded Python support to PythonSpec
pypa/virtualenv pull request #2809
Opened 2024-11-29 10:29 UTC by robsdedude

### Thanks for contributing, make sure you address all the checklists (for details on how see [development documentation](https://virtualenv.pypa.io/en/latest/development.html#development))

- [ ] ran the linter to address style issues (`tox -e fix`)
- [ ] wrote descriptive pull request text
- [ ] ensured there are test(s) validating the fix
- [ ] added news fragment in `docs/changelog` folder
- [ ] updated/extended the documentation

Closes: #2776

2025-01-10 06:09 UTC, gaborbernat commented on tox.ini
> +    3.13t
Would we not need support in tox for this?

2025-01-10 06:09 UTC, gaborbernat approved these changes

2025-01-10 06:10 UTC, gaborbernat approved these changes

2025-01-10 06:19 UTC, gaborbernat requested changes
Seems the CI is failing, can you fix it? @robsdedude Thanks

2025-01-10 15:51 UTC, robsdedude commented on tox.ini
> +    3.13t
I think I found a way by using an env var that points to the python executable and using that to explicitly configure tox with `base_python` to use that Python installation. I'm working on it.

2025-01-12 13:15 UTC, robsdedude commented on tox.ini
> +    3.13t
@gaborbernat maybe I've got something working now. Could you please re-trigger the CI?

2025-01-13 18:09 UTC, gaborbernat commented
@robsdedude seems it is still failing 🤔

2025-01-15 10:35 UTC, robsdedude commented
Now CI should pass. I made the CI run on my fork to increase the iteration velocity :upside_down_face:

2025-01-15 15:31 UTC, gaborbernat approved these changes

2025-01-15 15:42 UTC, merged

2025-01-16 17:52 UTC, ngoldbaum commented
Thanks so much for fixing this and seeing the PR through @robsdedude. Our team at Quansight Labs is trying to spot ecosystem issues like this around free-threaded Python. If you are aware of any other issues, we should chat!